
- hosts: all
  become: yes
  roles:
    - os_base
    - role: k8s-repository
      vars:
        k8s_main_ver: v1.30
        k8s_packages_ver: 1.30.1-1.1
    - k8s-pre_requirements
    - role: containerd
      vars:
        containerd_ver: 1.7.17
        runc_ver: 1.1.12
        cni_ver: 1.5.0