
- hosts: all
  become: yes
  roles:
    # - os_base
    # - k8s-repository
    - helm
    # - k8s-pre_requirements
    # - containerd
    # - k8s_setup/cluster_init
    # - k8s_setup/control_plain-node
    # - k8s_setup/worker-node
    # - k8s_setup/cni_calico
    # - lb_metallb
    # - ingress_nginx_controller


### Group Variables --> group_vars/all.yml