
- hosts: all
  become: yes
  roles:
    - os_base
    - k8s-repository
    - k8s-pre_requirements
    - containerd
    - k8s_setup/cluster_init
    - k8s_setup/control_plain-node
    - k8s_setup/worker-node
    - k8s_setup/cni_calico
    - k8s_setup/lb_metallb


### Group Variables --> group_vars/all.yml