
- hosts: all
  become: yes
  roles:
    - os/os_base
    - k8s/pre_requirements
    - os/containerd
    - k8s/repos
    - k8s/helm_client
    - bootstrap/cluster_init
    - network/calico
    - bootstrap/control_plane_node
    - bootstrap/worker_node
    - network/metallb
    - ingress/ingress_nginx
    - storage/nfs_csi
    - ingress/cert_manager
    - k8s/metrics_server


### Group Variables --> group_vars/all.yml