---

- name: Set hostname from inventory 
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Add K8s Endpoint to hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ k8s_cp_endpoint_ip }} {{ k8s_cp_endpoint }}"
    state: present

- name: Add inventory host for /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host].ansible_host | default(host) }} {{ hostvars[host].inventory_hostname }}
      {% endfor %}
    state: present

- name: update cache & upgrade base packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    state: latest
  when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "22.04"

- name: install base packages
  ansible.builtin.apt:
    name:
      - htop
      - curl
      - wget
      - git
      - vim
      - mc      
    state: present

- name: Add K8s admin user
  ansible.builtin.user:
    name: k8sadmin
    shell: /bin/bash
    uid: 2000
    expires: -1
    comment: K8s Admin User
    state: present


