---

- name:  Check swap in fstab 
  ansible.builtin.shell:
    cmd: grep swap /etc/fstab |grep -v ^# |awk '{print $1}' 
  register: swap_path 

- name:  Check swap file is enabled
  ansible.builtin.shell:
    cmd: swapon --show |awk 'NR==2'
  register: swap_check

- name:  Disable swap file 
  ansible.builtin.shell:
    cmd: swapoff -a
  when: swap_check.stdout != ""

- name: Remove swap in fstab
  ansible.posix.mount:
    src: "{{ swap_path.stdout }}"
    path: none
    fstype: swap
    opts: sw
    state: absent
  when: swap_path.stdout != ""

- name: Load kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - overlay
    - br_netfilter

- name: Set kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_set: true
  loop:
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }

- name: Reboot after K8s PRE Requiments
  ansible.builtin.reboot:
    test_command: uptime